import type { Metadata } from 'next'
import BookSalesTemplate from '@/components/BookSalesTemplate'
import type { BookData } from '@/components/BookSalesTemplate'

const bookData: BookData = {
  id: 'captain-eric-brown',
  title: 'Captain Eric "Winkle" Brown',
  subtitle: 'Captain of the Clouds, Test Pilot a Biography',
  price: 6.98,
  pageCount: 50,
  isbn: '9780957344365',
  publicationYear: 2015,
  description: `Background information on the flying life of the world's premiere test pilot. From his escapades in pre-war Germany to flying the Me 163 Komet this illustrated booklet is a mine of information. Explains his involvement with the invention of the Steam Catapult for aircraft carriers and its success in the US Navy. There is a rare drawing of the steam catapult included. The book also includes valuable references to articles and books he published. His lecture on Carrier Aviation to the United States Navy is included supported with rare illustrations. Over 50 pages A5 format with numerous black and white pictures including HMS Perseus and HMS Rocket out of Londonderry. There are pictures of his Hoverfly flight through smoke clouds generated by a Fiesler Storch and drawings of the steam catapult and images of German aircraft such as the Dornier Jet and Focke Wulf etc. Winkle Brown flew off the carrier vessel, HMS Argus a training post he disliked and her story is here. Into its tenth print due to popular demand, price held, highly sought after. Post Free.`,
  category: 'Aviation Biography',
  tags: ["Eric Brown","Test Pilot","Carrier Aviation","WWII","Aviation Biography"],
  imageUrl: '/book-covers/captain-eric-brown.jpg',
  ebayLink: 'https://www.ebay.co.uk/itm/123456789',
  features: [
    "Over 50 pages A5 format with numerous black and white pictures",
    "Includes HMS Perseus and HMS Rocket out of Londonderry",
    "Pictures of his Hoverfly flight through smoke clouds generated by a Fiesler Storch",
    "Drawings of the steam catapult and images of German aircraft",
    "Valuable references to articles and books he published",
    "His lecture on Carrier Aviation to the United States Navy included",
    "Rare drawing of the steam catapult included"
  ],
  academicRecognition: [
    "Used by aviation history courses",
    "Referenced in test pilot studies",
    "Cited in carrier aviation research"
  ],
  customerReviews: [
    {
      rating: 5,
      text: "Amazing pilot, all those 'planes, amazing",
      author: "eBay buyer",
      source: "eBay"
    },
    {
      rating: 5,
      text: "Very good communication, exactly as described, extremely well packaged and protected.",
      author: "Recent eBay buyer",
      source: "eBay"
    },
    {
      rating: 5,
      text: "Alan's book captures the essence of him well.",
      author: "Reader",
      source: "Review"
    },
    {
      rating: 5,
      text: "Loved the book",
      author: "Recent comment",
      source: "Review"
    },
    {
      rating: 5,
      text: "VERY QUICK DELIVERY, REALLY GOOD BOOK AND GREAT PRICE",
      author: "Recent buyer",
      source: "eBay"
    },
    {
      rating: 5,
      text: "Excellent overview of the world's greatest pilot.",
      author: "April 2023 purchase",
      source: "eBay"
    },
    {
      rating: 5,
      text: ".. it nevertheless makes a very worthwhile companion to 'Wings On My Sleeve'. Am very delighted.",
      author: "Recent buyer",
      source: "eBay"
    },
    {
      rating: 5,
      text: "...Excellent biography which I highly recommend",
      author: "Recent buyer",
      source: "eBay"
    }
  ]
}

const relatedBlogs: Array<{
  slug: string;
  title: string;
  excerpt: string;
  readTime: string;
}> = [
  {
    slug: "test-pilot-biography-eric-brown",
    title: "Test Pilot Biography: Eric Brown",
    excerpt: "Comprehensive biography of Captain Eric 'Winkle' Brown, the world's most experienced test pilot",
    readTime: "12 min read"
  }
]

const relatedBooks: Array<BookData> = []

export const metadata: Metadata = {
  title: 'Captain Eric "Winkle" Brown | Charles E. MacKay Books',
  description: `Background information on the flying life of the world's premiere test pilot. From his escapades in pre-war Germany to flying the Me 163 Komet this illustrated booklet is a mine of information.`,
  keywords: 'Eric Brown, Test Pilot, Carrier Aviation, WWII, Aviation Biography, Charles MacKay, aviation history books',
  openGraph: {
    title: 'Captain Eric "Winkle" Brown',
    description: `Background information on the flying life of the world's premiere test pilot. From his escapades in pre-war Germany to flying the Me 163 Komet this illustrated booklet is a mine of information.`,
    images: ['/book-covers/captain-eric-brown.jpg'],
    type: 'book'
  }
}

export default function BookPage() {
  return (
    <BookSalesTemplate 
      book={bookData}
      relatedBlogs={relatedBlogs}
      relatedBooks={relatedBooks}
    />
  )
}