name: Endpoint Health Checks

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *' # Daily at 06:00 UTC

jobs:
  check-endpoints:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check validator
        run: |
          set -euo pipefail
          curl -fsSL https://charlesmackaybooks.com/api/validate-feeds | head -c 700 || (echo "Validator endpoint failed" && exit 1)

      - name: Check products.xml
        run: |
          set -euo pipefail
          curl -fsSI https://charlesmackaybooks.com/products.xml | sed -n '1,20p'
          curl -fsSL https://charlesmackaybooks.com/products.xml | head -c 700

      - name: Check merchant-feed.txt
        run: |
          set -euo pipefail
          curl -fsSI https://charlesmackaybooks.com/merchant-feed.txt | sed -n '1,20p'
          curl -fsSL https://charlesmackaybooks.com/merchant-feed.txt | head -c 700

      - name: Check shopping-actions.xml
        run: |
          set -euo pipefail
          curl -fsSI https://charlesmackaybooks.com/shopping-actions.xml | sed -n '1,20p'
          curl -fsSL https://charlesmackaybooks.com/shopping-actions.xml | head -c 700

      - name: Check sitemap.xml
        run: |
          set -euo pipefail
          curl -fsSI https://charlesmackaybooks.com/sitemap.xml | sed -n '1,20p'
          curl -fsSL https://charlesmackaybooks.com/sitemap.xml | head -c 700


